### ISSUE TITLE
Preview of Home Page revision fails on some themes

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1143]
There is an issue with 3.5.5. version

Preview revisions on Homepage, will show blog archive

This is only happens with homepage. All pages/posts working fine

Tested using: Kadence theme

Video: https://www.loom.com/share/b39d9ebe43524e4caf80926269c13cd5

**Comment by agapetry** [comment]
@rizaardiyanto1412 @stevejburge I'll have to resolve this with a plugin setting because:

- With some themes, previews of saved revisions will not display correctly if the URL uses preview argument
- With some themes, previews of saved revisions will not display correctly if the URL does not use preview argument

**Comment by agapetry** [comment]
This change is included in the following pre-release package:

https://github.com/publishpress/PublishPress-Revisions/releases/tag/v3.5.6-rc

**Comment by rizaardiyanto1412** [comment]
@agapetry I'm still able to replicate this with the setting checked or unchecked on 3.5.6 stable version.

**Comment by flexcodenet** [comment]
Same here at 3.5.6. We use custom theme + Visual Composer.

Before update we use Version 3.1.13 and all work correct.

**Comment by flexcodenet** [comment]
Preview displays the view for the post list - index.php.
