### ISSUE TITLE
Missing screen element metabox

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1179]
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/76724544-5970-4b32-abfc-c102c3bdc0c7)
When Revisions active

![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/9fdb9c4d-ecbf-4426-8bca-30b5dd5c2d6e)

When revisions deactivated

**Comment by agapetry** [comment]
The Custom Fields element is supported in the current plugin release. The other fields in question (Comments, Slug and Author) are intentionally removed from the revision edit UI due to limitations with the plugin's interaction with the post data schema. In the case of Author, a replacement dropdown is provided within the Publish metabox instead.
