### ISSUE TITLE
"Revision Archive" feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#25]
One useful feature for PublishPress Revisions would be a centralized log of all the revisions on a site.

It would be like https://wordpress.org/plugins/simple-history/ but only for content revisions.

There would be filters on top. Perhaps the default filter would be "Published" so at first glance people could see new changes to site content.

**Comment by Drumbell** [comment]
This would be a fantastic addition! A rejected filter would enable admins/members to watch if someone is irresponsibly rejecting good additions. Should state who did what action.

For the Published filter would be great if it too had a compare feature so that people can see what has changed. Works perfect in Queue. Due to Queue clearing the records would be good if the log feature also included the comparison. If we got extra fancy it could display in a modal:

![modal](https://user-images.githubusercontent.com/4361528/67173439-8df5de00-f373-11e9-9a48-8d3c6d09b17b.png)

Within the comparison modal we could have arrows that navigate to the next log item to see it's changes. This would make it much easier for admins to overlook the latest changes to posts that have been changed through Revisions Pro.

**Comment by stevejburge** [comment]
One user has requested a screen where people can browse revisions. Here's his use-case

> I wish for Contributors to be able to review the revision history after I've already published the posts so they can see the edits I made so that they can learn/improve (but without being able to make further changes).

**Comment by TheChallenging** [comment]
> One user has requested a screen where people can browse revisions.

Sounds interesting. However I'm failing to understand it's importance given we can compare between each revision of a post. If I understand right there's a proposal to see revisions of revisions? I'm not saying it wouldn't be potentially helpful, however sounds a bit complicated to make. Current revision comparison gives a pretty good idea of things added between each version but doesn't "show each micro step". Perhaps this could be optional from Revisions Pro's settings? Placement wise could have a button called "Steps for Revision" which shows a revisions revisions; showing the history of that revision.

![Steps for Revision](https://user-images.githubusercontent.com/4361528/76127347-4a181400-5fb6-11ea-93fb-2297100b485f.png)

**Comment by stevejburge** [comment]
@TheChallenging One way I imagine this is a bit like the "Posts" screen, but for revisions.

You would be able to browse through all the revisions for any post.

Revisions created through PublishPress Revisions would appear there, alongside normal revisions.

**Comment by stevejburge** [comment]
Maybe we can use this layout from the "manage" screen and just extend it with filters:

<img width="992" alt="revisions-overview" src="https://user-images.githubusercontent.com/3868028/96755424-b5c1bc80-13a0-11eb-9a2f-23c1b2496305.png">

**Comment by DaringDreams** [comment]
It would be neat if there was another section called "Revision Archive" which could go to /wp-admin/admin.php?page=rvy-revisions

![Revision Archive](https://user-images.githubusercontent.com/4361528/96835297-41b30300-13f8-11eb-9dbb-0c7a916264b0.png)

From Revision Archive one could filter to see past revisions similar to the above screen shot but without needing to be assigned to a specific post until searched. If accessed from **Edit Post > Revisions > Manage** it could look something like this:

![History](https://user-images.githubusercontent.com/4361528/96835578-a1a9a980-13f8-11eb-87f5-b52c03180ec8.png)

This would allow for quick navigation to other revision archives and help with managing them.

**Comment by stevejburge** [comment]
+1 @DaringDreams, yes - this is the direction I'd like to go also

**Comment by stevejburge** [comment]
One more request, this time from a user who wants long-term storage for WooCommerce data:

> - Does this cover product images in version history ?
> - How many items does this cover in version history ?

**Comment by stevejburge** [comment]
> It is also important that there is some sort of audit history of who edited / approved each page in the Workflow

**Comment by stevejburge** [comment]
One more:

> a feature that would be great to have is some sort of history on what was approved, by who etc.

**Comment by ArcticSnowman** [comment]
This feature is very important in an enterprise setting, as there can be a need to show who made changes and who approved the change to a web site for compliance purposes.

**Comment by stevejburge** [comment]
Thanks @ArcticSnowman 

Our team have built a platform that can do this now at https://logtivity.io/

However, in the months to come, we do also plan to add a log directly into Revisions also

**Comment by stevejburge** [comment]
2 more this week. Including this:

> can the plugin keep track / history of each product revision done eg product a had 5 revisions today, B 3 revisions, could you restore these revisions at any given time ? this includes restoring content, meta , categories, prices etc

**Comment by stevejburge** [comment]
@agapetry This continues to be our most popular feature request: 

> We need something that logs ALL changes / Edits made to the content.

**Comment by htmgarcia** [comment]
@stevejburge first draft. Please note the filters are missing.

![Screen Shot 2023-03-02 at 17 24 45](https://user-images.githubusercontent.com/4999794/222586650-4a9db5f1-ef7d-474e-8eb4-298119c8d709.png)

![Screen Shot 2023-03-02 at 17 25 41](https://user-images.githubusercontent.com/4999794/222586695-bc0d7640-fd97-4a3b-a00a-8aa44b303393.png)

**Comment by stevejburge** [comment]
@htmgarcia Awesome start, thanks. I'll loop in @agapetry  

I wonder if the main screen should have 5 columns?

1. Published date
2. Author
3. Revision date
4. Revised by (user)

**Comment by stevejburge** [comment]
One more request for data: the total number of revisions on that post

**Comment by agapetry** [comment]
Thanks, @htmgarcia.  This ia good groundwork. As you implied, it will be all about the filtering - probably including default filtering.  I'm not sure how useful a listing of every revision of every post of every type could be ;)

Unless the filtering will limit the view to a single post type at a time, the table will need a Post Type column.  You might also consider a "Preview" and "Delete" row action links, for times when navigating through the Compare screen or the bulk delete button is inefficient.

Due to Revisions options for post date handling, causing the "Published Date" field to always retain original publication will require a new post_meta row.  We also talked about integrating some post_meta fields about publication method (direct edit, submitted revision or scheduled revision) as well as "Approved By" where applicable . Those rows don't exist yet, but also imply the need for columns on this screen. Actually, once custom statuses are implemented for revisions, multiple users could be involved in approving through various workflow statuses. I think it would be reasonable to plan on indicating those as comma-delimited names in an "Approved By" column, leaving the possibility of custom development adding dedicated columns for specific approval stages.

Finally, I think it would be convenient to include a "Has Revision" or "Queue" row action link as we have in the regular Posts / Pages table. That would serve as both a flag that additional revision(s) are in process, and a link to drill into those in Revision Queue.

**Comment by stevejburge** [comment]
@agapetry @htmgarcia 

- A listing of every revision of every post type should be useful if we add good filter. Maybe we start with "Posts" and "Pages" selected by default?
- Yes to a "Post Type" column.
- I'm thinking that actions should probably be placed on a "Quick Edit" row underneath the title?

**Comment by stevejburge** [comment]
OK, this feature is going to need it's own milestone soon More feedback:

> The list reminds me of a “recently edited posts” list. In the admin,  it might be nice to have child menu item in posts called `Recent` to quickly access things I’ve worked on recently. Eg. I use the ‘Recent’ link in Google Drive all the time.

**Comment by htmgarcia** [comment]
@stevejburge @agapetry 

Current progress:
![Screen Shot 2023-03-09 at 14 11 03](https://user-images.githubusercontent.com/4999794/224143657-45128ff2-f050-4a8b-8a61-d5404c34525b.png)

According to my tests, by default an administrator user doesn't have the capabilities to delete a revision post type, so the delete link in row actions is not possible.

![Screen Shot 2023-03-09 at 14 11 13](https://user-images.githubusercontent.com/4999794/224143686-153ed04c-cc18-4090-b485-e97daea5b01a.png)

> One more request for data: the total number of revisions on that post

May you elaborate?

> A listing of every revision of every post type should be useful if we add good filter. Maybe we start with "Posts" and "Pages" selected by default?

Currently only Posts and Pages types are available as filters

> I'm thinking that actions should probably be placed on a "Quick Edit" row underneath the title?

You mean a quick edit as regular published posts?

**Comment by agapetry** [comment]
>>  I'm thinking that actions should probably be placed on a "Quick Edit" row underneath the title?

> You mean a quick edit as regular published posts?

I think what's meant is the row action links which display on hover. We shouldn't be quick-editing revisions.

**Comment by htmgarcia** [comment]
@agapetry if you have a chance to test, this is the branch https://github.com/publishpress/PublishPress-Revisions/compare/development...ppr-25

**Comment by agapetry** [comment]
@htmgarcia I installed your branch and briefly reviewed the query code. It looks basically correct. I'll follow with a correction for the preview link.

**Comment by htmgarcia** [comment]
@stevejburge @agapetry a couple of improvements.

Add compare links for posts only if revisions is enabled for its post type.
![Screen Shot 2023-03-23 at 20 09 03](https://user-images.githubusercontent.com/4999794/227409360-740b4b25-64b6-41bf-9735-8a8a8fb92cc2.png)


Improved friendly date time. If a revision match current year, we skip the year in the date:
![Screen Shot 2023-03-23 at 20 32 30](https://user-images.githubusercontent.com/4999794/227409592-66e99687-70ed-46e2-a307-b6f1c608d6a3.png)

**Comment by JoshJourney** [comment]
Looks great. Date format wise this is my favourite format, but I recognize that other parts of the world put the day before the month. It should be based on the WP General Settings 'Date Format' along with the 'Time Format' set by the admin. That being said for the sake of keeping it clean (just like the screenshot above) I'm in favour of removing the year for simplicity. In other words 'admin designated date/time format' minus the year.

**Comment by htmgarcia** [comment]
@stevejburge @agapetry now the datetime uses settings formats.

@JoshJourney since we're using the date format from WordPress general settings we're keeping the year. 

![Screen Shot 2023-03-29 at 20 11 33](https://user-images.githubusercontent.com/4999794/228710148-bd349035-2388-492e-bb86-e203e01181a3.png)

**Comment by stevejburge** [comment]
Added in 3.4.0
