### ISSUE TITLE
Allow anyone to create revisions immediately

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#6]
At the moment, only the "Revisor" user gets immediate use from the Revisionary plugin. That makes it hard to get started and to configure.

Maybe we should make this "Save as Pending Revision" box available to everyone immediately:

<img width="296" alt="save-as-pending-revision" src="https://user-images.githubusercontent.com/3868028/58965622-e179dd80-877e-11e9-8aa0-390bba5d317c.png">

**Comment by stevejburge** [comment]
Solved in 2.0

**Comment by Drumbell** [comment]
Been busy the last week but am back on board. Testing Revisionary Pro today. Perhaps I misunderstood this PR but it seems users of the author role cannot submit revisions to other author's posts.

![no edit](https://user-images.githubusercontent.com/4361528/66509970-f21dc580-ea88-11e9-946c-5e57a43b8b86.png)

When using Capabilities Manager "Edit others" on posts either allows for editing any post without approval or no ability to submit a revision. I'm aware it's not Capabilities Manager's job to handle this but figured it was worth a shot. As stated at the top:

> At the moment, only the "Revisor" user gets immediate use from the Revisionary plugin. That makes it hard to get started and to configure.

Ideally other usergroups be able to submit revisions. Perhaps have a backend select field that chooses which user groups to include. This way if we wanted editors to "politely suggest" a revision that is approved by the original author we still could while possibly making them able to approve it in Revision Queue. The most important piece is having author's be able to make revisions.

**Comment by stevejburge** [comment]
@Drumbell Yes, PublishPress Revisions tries not to mess with the default WordPress permissions.

You're right to use Capability Manager to customize this. We already have at least two plugins that modify permissions and we didn't want to introduce another with PublishPress Revisions

**Comment by Drumbell** [comment]
> We already have at least two plugins that modify permissions and we didn't want to introduce another with PublishPress Revisions

I think we are on the same page regarding tampering with permissions, I'm only concerned with Revisions. Used "Capabilities Manager" to test what was possible. When you activate Revisions Pro a Revisor doesn't get elevated edit privileges but does get the ability to submit a revision to a post. Ideally other user groups could also submit a revision to a post so that they too can contribute to peoples post's. Specifically it would be awesome if an author (usergroup) could submit to another author's post. Right now only a revisor can submit a revision to another user's post except admins.

Because a Revisor cannot edit their own post's without needing approval it would be handy to allow authors and above to do so as well. There are other benefits such as "Promoted Users" (users who deserve more privileges but still shouldn't be allowed to edit all posts without approval); in other words a user in the usergroup "Top Contributors". Would have a script that allows them to upload more photos, full resolution, no post restrictions, ect. By default WP has users assigned to a single usergroup. I'm aware there are ways to override this but with permissions this can get trickier/problematic.

**Comment by stevejburge** [comment]
@agapetry Thoughts on this?

In the bigger picture, it's relatively harmless to allow Authors to submit revisions to other people's posts. Nothing gets published, after all.

But is changing this behavior best left to another plugin like CME?
